data:
  path: "/home/space/datasets"

model:
  hidden_size: 768
  num_layers: 12
  num_heads: 12
  max_position_embeddings: 512
  vocab_size: 30522

training:
  batch_size: 32
  learning_rate: 0.00001
  num_epochs: 3
